services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: goods-app
    restart: unless-stopped
    ports:
      - "18732:3000"
    env_file:
      - .env
    volumes:
      # 直接挂载宿主机本地目录，确保已有图片可见
      - ./public/uploads:/app/public/uploads
